<a href="https://colab.research.google.com/github/JonkerMotumi/DWPM-Mixture-Model/blob/master/Linear_Algrebara_Matix_mal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create two random 4x4 matrices
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)

In [9]:
print(A)
print(A[1,1])

[[0.55545044 0.40417801 0.33368966 0.38600861]
 [0.72435982 0.62721886 0.37530917 0.41823018]
 [0.74330354 0.24765018 0.79143161 0.75229737]
 [0.38200778 0.10904156 0.65461184 0.73250722]]
0.6272188604551779


In [11]:
rows_A, cols_A = A.shape

print(rows_A)

4


In [18]:
def manual_matmul(A, B):
    # Get dimensions
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Initialize the result matrix with zeros
    result = np.zeros((rows_A, cols_B))

    # TODO: Implement triple nested loops here
    for i in range(rows_A):
        ans=0
        for j in range(cols_B):
            ans=0
            for k in range(cols_A):
                x = A[i,k]
                y = B[k,j]
                ans = ans + x*y
                result[i,j]= ans

    return result

In [28]:
manual=manual_matmul(A,B)
official = np.matmul(A, B)
print(manual)
print(official)
print(f"Match found: {np.allclose(manual, official)}")

[[0.95053079 1.26357038 0.79894267 0.97734037]
 [1.14275389 1.65367333 0.96107691 1.29817084]
 [1.59614775 1.74984425 1.4379025  1.37785057]
 [1.22617691 1.24929955 1.18031096 0.9376061 ]]
[[0.95053079 1.26357038 0.79894267 0.97734037]
 [1.14275389 1.65367333 0.96107691 1.29817084]
 [1.59614775 1.74984425 1.4379025  1.37785057]
 [1.22617691 1.24929955 1.18031096 0.9376061 ]]
Match found: True
